### ISSUE TITLE
Feature: Wire in guetzli for jpg images

### ISSUE THREAD

**Issue by zeroasterisk** [zeroasterisk/optim#2]
Try out:
https://github.com/imagemin/imagemin-guetzli

- Should it replace the other jpg plugins?
- Should it work along side the other jpg plugins?
- Should we manually run with 2+ jpg plugins and choose the smallest resulting file/buffer?

**Comment by mowsmith** [comment]
Guetzli is up and running. 

Right now imagemin is running both guetzli and mozjpeg{quality: 95} (according to the mozjpeg repo, it's not a good idea to set quality above 95 because file size can increase and there isn't really a distinguishable difference). Guetzli for file reduction and mozjpeg for progressive encoding to shrink it a bit further. Guetzli is very slow, but this shouldn't be an issue because, even for large images, it finishes well before the lambda will timeout. 

Going to close this for now because there seems to be no reason not to just run them both at the moment. If need be, it can be reopened or a new issue created to test it with broken jpegs to see if it might correct them.
